base/urls.py
# app_name/urls.py

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'app_name'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('product/', views.product_list, name='product_list'),
    path('product/', views.product, name='product'),
    path('product/add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('productdetails/', views.product_list2, name='product_list2'),
    path('productdetails/', views.productdetails, name='productdetails'),
    path('productdetails/add_to_order/', views.add_to_order, name='add_to_order'),
    path('productdetails2/', views.product_list3, name='product_list3'),
    path('productdetails2/', views.productdetails2, name='productdetails2'),
    path('productdetails2/add_to_order/', views.add_to_order, name='add_to_order'),
    path('productdetails3/', views.product_list4, name='product_list'),
    path('productdetails3/', views.productdetails3, name='productdetails3'),
    path('productdetails3/add_to_order/', views.add_to_order, name='add_to_order'),
    path('registration/', views.registration, name='registration'),
    path('login/', views.custom_login, name='login'),
    path('games/update_rewards_table/', views.update_rewards_table, name='update_rewards_table'),
    path('games/', views.games, name='games'),
    path('games/update_rewards_table/', views.update_rewards_table, name='update_rewards_table'),
    path('about/', views.about, name='about'),
    path('logout/', views.custom_logout, name='logout'),
    path('get_cart_items/',views.get_cart_items, name='get_cart_items'),
    
]

mywebproject/urls.py
from django.contrib import admin
from django.urls import path, include
from base.views import index 

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', index, name='index'),  
    path('index/', include('base.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('base.urls')),
    
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer_table(models.Model):
    username = models.CharField(max_length=50)
    email = models.EmailField()
    password = models.CharField(max_length=128)
    age = models.PositiveIntegerField(null=True, blank=True)
    location = models.CharField(max_length=100, blank=True)
    
class Products_table(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=100)
    stock = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.product_name

class OrderingTable(models.Model):
    customer_name = models.CharField(max_length=50)
    product_id = models.ForeignKey(Products_table, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    product_name = models.CharField(max_length=50)

class Cart(models.Model):
    customer_name = models.CharField(max_length=50)  # Change customer_id to customer_name
    product = models.ForeignKey(Products_table, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Cart ID: {self.id}, Customer: {self.customer_name}, Product: {self.product.product_name}"
    
class RewardsTable(models.Model):
    customer_name = models.CharField(max_length=100)
    rewards = models.CharField(max_length=100)
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.customer_name} - {self.rewards} - {self.quantity}"

base/forms.py
from django import forms
from django.contrib.auth.models import User

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Username is already taken')
        return username

base/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login ,logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib import messages
from .models import Customer_table
from .forms import UserRegistrationForm
from django.db import connection
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.http import JsonResponse
from django.db import connection, transaction
from django.http import HttpResponse
from .models import Products_table,Cart
from datetime import date
from django.utils import timezone

def index(request):
    print('Entered Index')
    return render(request, 'base/index.html')

def product(request):
    print('Entered Product')
    return render(request, 'base/product.html')

def productdetails(request):
    print('Entered ProductDetails')
    return render(request, 'base/productdetails.html')

def productdetails2(request):
    print('Entered ProductDetails')
    return render(request, 'base/productdetails2.html')

def productdetails3(request):
    print('Entered ProductDetails')
    return render(request, 'base/productdetails3.html')

def cart(request):
    print('Entered Cart')
    return render(request, 'base/cart.html')

def games(request):
    print('Entered Games')
    return render(request, 'base/games.html')

def about(request):
    print('Entered About')
    return render(request, 'base/about.html')

def registration(request):
    print('Entered registration form')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()  
            email = request.POST.get('register-email', '')
            location = request.POST.get('location', '')
            age = request.POST.get('age', None)
            print(f"Email: {email}, Location: {location}, Age: {age}")
            customer = Customer_table.objects.create(
                username=user.username,
                email=email,
                password=user.password,
                age=age,
                location=location
            )
            print('Customer object created')
            
            messages.success(request, 'Registration successful', 'register')
            return redirect('app_name:login')
        else:
            messages.error(request, 'Registration failed. Please check the form.', 'register')
    return render(request, 'base/registration.html')

def custom_login(request):
    print('Entered Login form')
    if request.method == 'POST':
        if 'login-username' in request.POST:
            username = request.POST['login-username']
            password = request.POST['login-password']
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, 'Login successful', 'login')
                return redirect('app_name:index')
            else:
                messages.error(request, 'Invalid login credentials', 'login')
    return render(request, 'base/login.html')

def custom_logout(request):
    print('Entered Logout')
    logout(request)
    return redirect('app_name:index')


def get_cart_items(request):
    print('Entered getCart')
    cart_items = [
        {'id': product.id, 'name': product.product_name, 'price': product.product_price, 'image': product.product_image.url}
        for product in Products_table.objects.all()
    ]
    print('returning Cart items')
    return JsonResponse(cart_items, safe=False)

def product_list(request):
    print('Entered Productlist')
    products = Products_table.objects.all()
    print(products)
    return render(request, 'base/product.html', {'products': products})

def product_list2(request):
    print('Entered Productlist2')
    products = Products_table.objects.all()
    print(products)
    return render(request, 'base/productdetails.html', {'products': products})

def product_list3(request):
    print('Entered Productlist2')
    products = Products_table.objects.all()
    print(products)
    return render(request, 'base/productdetails2.html', {'products': products})

def product_list4(request):
    print('Entered Productlist2')
    products = Products_table.objects.all()
    print(products)
    return render(request, 'base/productdetails3.html', {'products': products})

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .models import Cart, Products_table

@login_required
def add_to_cart(request):
    print('ENTER add to cart')
    if request.method == 'POST':
        user = request.user
        print(user)
        if user.is_authenticated:
            print('getting product_id')
            product_id = request.POST.get('product_id')
            print(product_id)
            quantity = int(request.POST.get('quantity', 1))
            print(quantity)
            if not product_id:
                return JsonResponse({'success': False, 'message': 'Product ID is missing or empty.'})

            print('Fetching product using raw SQL query')
            with connection.cursor() as cursor:
                cursor.execute("SELECT * FROM base_products_table WHERE product_id = %s", [product_id])
                product_row = cursor.fetchone()

            if product_row:
                product = {
                    'product_id': product_row[0],
                    'product_name': product_row[1],
                    'stock': product_row[2],
                    'price': product_row[3]
                }
                print(product)
            else:
                return JsonResponse({'success': False, 'message': 'Product not found.'})
            created_at = timezone.now()
            print('Updating cart table using raw SQL query')
            with connection.cursor() as cursor:
                cursor.execute(
                    "INSERT INTO base_cart (customer_name,quantity,created_at,product_id) "
                    "VALUES (%s, %s, %s,%s)",
                    [user,quantity,created_at,product_id]
                )

            

            return JsonResponse({'success': True, 'message': 'Product added to cart successfully.'})
        else:
            return JsonResponse({'success': False, 'message': 'User is not authenticated.'})

    return JsonResponse({'success': False, 'message': 'Invalid request method.'})
    
def add_to_order(request):
    print('Entered add to order')
    if request.method == 'POST':
        user = request.user
        print(user)
        if user.is_authenticated:
            print('getting product_id')
            product_id = request.POST.get('product_id')
            print(product_id)
            quantity = int(request.POST.get('quantity', 1))
            print(quantity)
            if not product_id:
                return JsonResponse({'success': False, 'message': 'Product ID is missing or empty.'})

            print('Fetching product using raw SQL query')
            with connection.cursor() as cursor:
                cursor.execute("SELECT * FROM base_products_table WHERE product_id = %s", [product_id])
                product_row = cursor.fetchone()
                product_name=product_row[1]
                stock=product_row[2]
            if product_row:
                product = {
                    'product_id': product_row[0],
                    'stock': product_row[2],
                    'price': product_row[3]
                }
                print(product)
            else:
                return JsonResponse({'success': False, 'message': 'Product not found.'})
            if stock <= 0:
                return JsonResponse({'success': False, 'message': 'Out of stock.'})
            created_at = timezone.now()
            print('Updating cart table using raw SQL query')
            with connection.cursor() as cursor:
                cursor.execute(
                    "INSERT INTO base_orderingtable (customer_name,created_at,product_name,product_id_id) "
                    "VALUES (%s, %s, %s,%s)",
                    [user,created_at,product_name,product_id]
                )

            print('Decrementing product stock using raw SQL query')
            with connection.cursor() as cursor:
                cursor.execute(
                    "UPDATE base_products_table SET stock = stock - %s WHERE product_id = %s",
                    [quantity, product_id]
                )
            return JsonResponse({'success': True, 'message': 'Product Ordered successfully.'})
        else:
            return JsonResponse({'success': False, 'message': 'User is not authenticated.'})

    return JsonResponse({'success': False, 'message': 'Invalid request method.'})

from django.http import JsonResponse
from django.db import connection

def update_rewards_table(request):
    print('Entered rewards view')
    if request.method == 'POST':
        user = request.user
        print(user)
        customer_id = request.user.id
        prize = request.POST.get('prize')
        print(prize)
        try:
            with connection.cursor() as cursor:
                cursor.execute(
                    "SELECT * FROM base_rewardstable WHERE customer_name = %s AND rewards = %s",
                    [user, prize]
                )
                existing_reward = cursor.fetchone()

            if existing_reward:
                with connection.cursor() as cursor:
                    cursor.execute(
                        "UPDATE base_rewardstable SET quantity = quantity + 1 WHERE customer_name = %s AND rewards = %s",
                        [user, prize]
                    )
            else:
                with connection.cursor() as cursor:
                    cursor.execute(

base/templates/base/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'base/css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">

    <style>

        body {
            font-family: 'Poppins', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f8f8f8;
        }

        header {
            background-color: #333;
            color: #fff;
            padding: 10px;
            text-align: center;
        }

        main {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1,
        h2 {
            color: #333;
        }

        p {
            line-height: 1.6;
            color: #555;
        }

        img {
            max-width: 100%;
            height: auto;
            border-radius: 4px;
            margin-top: 20px;
        }
    </style>
    <title>About Us - Textiles & Shoes -VinoStore</title>
</head>

<body>

    <div class="navbar">
        <div class="logo">
            <a href="{% url 'app_name:index' %}"><img src="{% static 'base/css/images/Vinostore.jpeg' %}" width="125px"></a>
        </div>
        <nav>
            <ul id="MenuItems">
                <li><a href="{% url 'app_name:index' %}">Home</a></li>
                <li><a href="{% url 'app_name:product' %}">Products</a></li>
                <li><a href="{% url 'app_name:about' %}">About Us</a></li>
                <li><a href="{% url 'app_name:registration' %}">Register</a></li>
                    <li><a href="{% url 'app_name:login' %}">Login</a></li>
                <li><a href="{% url 'app_name:games' %}">Spin Games</a></li>
            </ul>
        </nav>
        <a href="{% url 'app_name:cart' %}"><img src="{% static 'base/css/images/cart.png' %}" width="25px" height="25px"></a>
        <img src="{% static 'base/css/images/menu.png' %}" class="menu-icon" onclick="menutoggle()">
    </div>

    <main>
        <!-- Your About page content goes here -->
        <p>Welcome to Vinoth Stores, Your premier destination for high-quality textiles and stylish shoes.</p>

        <p>At Textile & Shoes, we are passionate about providing our customers with the finest products. Our curated collection
            includes a wide range of textiles, from luxurious fabrics to trendy shoes that suit every style.</p>
        <br>
        <p>Founded in 2024, we have been committed to delivering exceptional quality and unparalleled customer service. Our team
            of experts carefully selects each item to ensure that our customers receive the best in comfort, style, and
            durability.</p>
        <br>
        <p>Whether you are looking for elegant textiles to enhance your home decor or the latest footwear trends to elevate your
            fashion game, we've got you covered. Our commitment to quality and customer satisfaction sets us apart in the world
            of online shopping.</p>
        <br>

        <p>Explore our collection and experience the joy of shopping for premium textiles and shoes from the comfort of your home.
            Thank you for choosing Textile & Shoes for all your fashion needs.</p>
        <br><br>

        <div class="partners">
            <h2>Our Partners</h2>
            <img class="partner-logo" src="{% static 'base/css/images/raymond.jpg' %}" alt="Partner 1" />
            <img class="partner-logo" src="{% static 'base/css/images/peter.jpg' %}" alt="Partner 2" />
            <img class="partner-logo" src="{% static 'base/css/images/adidas.jpg' %}" alt="Partner 3" />
            <img class="partner-logo" src="{% static 'base/css/images/nike.jpg' %}" alt="Partner 4" />
            <img class="partner-logo" src="{% static 'base/css/images/h&m.jpg' %}" alt="Our Team" />
        </div>
    </main>

    <footer>
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="footer-col-1">
                        <h3>Download our App</h3>
                        <p>Download App for Android and iOS Mobiles</p>
                        <div class="app-logo">
                            <img src="{% static 'base/css/images/play-store.png' %}">
                            <img src="{% static 'base/css/images/app-store.png' %}">
                        </div>
                    </div>
                    <div class="footer-col-2">
                        <img src="{% static 'base/css/images/Vinostore.jpeg' %}">
                        <p>Shop Smart, Live Stylishly: Your One-Stop E-destination for Fashion and Function.</p>
                    </div>
                    <div class="footer-col-3">
                        <h3>Useful Links</h3>
                        <ul>
                            <li>Coupons</li>
                            <li>Return Policy</li>
                            <li>Blog post</li>
                            <li>Join Affiliates</li>
                        </ul>
                    </div>
                    <div class="footer-col-4">
                        <h3>Follow us</h3>
                        <ul>
                            <li>Facebook</li>
                            <li>Twitter</li>
                            <li>Instagram</li>
                            <li>YouTube</li>
                            <li>Threads</li>
                        </ul>
                    </div>
                </div>
                <hr>
                <div class="copyright">
                    <p>CopyRight 2023-Vinoth Website</p>
                </div>
            </div>
        </div>
    </footer>
    <!--js toggle menu-->
    <script>
        var MenuItems = document.getElementById("MenuItems");
        MenuItems.style.maxHeight = "0px";

        function menutoggle() {
            if (MenuItems.style.maxHeight == "0px") {
                MenuItems.style.maxHeight = "200px";
            } else {
                MenuItems.style.maxHeight = "0px";
            }
        }
    </script>
</body>

</html>

base/templates/base/cart.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{%static 'base/css/style.css'%}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap" rel="stylesheet">
        <title>Cart - VinoStore</title>
        
        <style>
            select {
                padding: 10px;
                font-size: 16px;
                border: 1px solid #ccc;
                border-radius: 4px;
                background-color: #fff;
                color: #333;
                appearance: none;
                width: 200px;
            }
    
            select option {
                padding: 10px;
                font-size: 14px;
                background-color: #f5f5f5;
                color: #333;
            }
    
            select:hover {
                background-color: #00c3ff75;
            }
    
            input {
                width: 100px;
                height: 37px;
            }
        </style>
    </head>
    <body>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.3/html2pdf.bundle.min.js"></script>
        <script>
        function downloadPDF() {
        var element = document.getElementById('cartTable');
        var opt = {
            margin:       1,
            filename:     'cart.pdf',
            image:        { type: 'jpeg', quality: 0.98 },
            html2canvas:  { scale: 2 },
            jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
        };
        var userName = "Hello, Dear Customer Your Bill is Here";
        var vinocartLogo ="../base/css/images/Vinostore.jpeg";

        var userNameElement = document.createElement('div');
        userNameElement.textContent =  userName;

        var logoElement = document.createElement('img');
        logoElement.src = vinocartLogo;
        logoElement.style.width = "100px";
        element.prepend(userNameElement);
        element.parentNode.insertBefore(logoElement, element); 
        html2pdf().set(opt).from(element).save();
    }
</script>
    
        <div class="container">
            <div class="navbar">
                <div class="logo">
                    <a href="{% url 'app_name:index' %}""><img src="{% static 'base/css/images/Vinostore.jpeg' %}" width="125px"></a>
                </div>
                <nav>
                    <ul id="MenuItems">
                        <li><a href="{% url 'app_name:index' %}"">Home</a></li>
                        <li><a href="{% url 'app_name:product' %}"">Products</a></li>
                        <li><a href="{% url 'app_name:about' %}"">About</a></li>
                        <li><a href="{% url 'app_name:registration' %}">Register</a></li>
                        <li><a href="{% url 'app_name:login' %}">Login</a></li>
                        <li><a href="{% url 'app_name:games' %}"">Spin Games</a></li>

                    </ul>
                </nav>
                <a href="{% url 'app_name:cart' %}"><img src="{% static 'base/css/images/cart.png' %}" width="25px" height="25px"></a>
                <img src="{% static 'base/css/images/menu.jpg'%}" class="menu-icon" onclick="menutoggle()">

            </div>
            
    </div>
</div>

<!--cart item details-->
<div class="small-container cart-page" id="cartTable">
    <table id="cartTable">
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th id="subtotal">SubTotal</th>
        </tr>
        <tr>
            <td>
                <div class="cart-info">
                    <a href="{% url 'app_name:productdetails' %}""><img src="{% static 'base/css/images/buy-1.jpg' %}" width="125px"></a>

                    <div>
                        <p>Red Printed TShirt</p>
                        <small class="price">Price:$50.00</small>
                        <a href="#" onclick="removeCartItem(this)">Remove</a>
                    </div>
                </div>
            </td>
            <td><input type="number" value="1" onchange="updateCartItem(this)"></td>
            <td class="subtotal">$50.00</td>
        </tr>

        <tr>
            <td>
                <div class="cart-info">
                    <a href="{% url 'app_name:productdetails2' %}""><img src="{% static 'base/css/images/buy-3.jpg ' %}"></a>
                    <div>
                        <p>Black Pant</p>
                        <small class="price">Price:$100.00</small>
                        <a href="#" onclick="removeCartItem(this)">Remove</a>
                    </div>
                </div>
            </td>
            <td><input type="number" value="1" onchange="updateCartItem(this)"></td>
            <td class="subtotal">$100.00</td>
        </tr>
        <tr>
            <td>
                <div class="cart-info">
                    <a href="{% url 'app_name:productdetails3' %}"><img src="{% static 'base/css/images/buy-2.jpg' %}"></a>
                    <div>
                        <p>Black Shoes</p>
                        <small class="price">Price:$40.00</small>
                        <a href="#" onclick="removeCartItem(this)">Remove</a>
                    </div>
                </div>
            </td>
            <td><input type="number" value="1" onchange="updateCartItem(this)"></td>
            <td class="subtotal">$40.00</td>
        </tr>
    </table>
    <div class="total-price">
        <table>
            <tr>
                <td>SubTotal</td>
                <td id="subTotal">$50.00</td>
            </tr>
            <tr>
                <td>Tax (20%)</td>
                <td id="tax">$10.00</td>
            </tr>
            <tr>
                <td>Total</td>
                <td id="total">$60.00</td>
            </tr>
        </table>
    </div>
</div>
<button style="margin-left: 80%;" class="btn" onclick="downloadPDF()">Download PDF</button>


    <!--footer-->
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col-1">
                    <h3>Download our App</h3>
                    <p>Download App for Andriod and IOS Mobiles</p>
                    <div class="app-logo">
                        <img src="{% static 'base/css/images/play-store.png' %}">
                        <img src="{% static 'base/css/images/app-store.png '%}">
                    </div>
                </div>
                <div class="footer-col-2">
                    <img src="{% static 'base/css/images/Vinostore.jpeg' %}">
                    <p>Shop Smart, Live Stylishly: Your One-Stop E-destination for Fashion and Function.</p>
                </div>
                <div class="footer-col-3">
                    <h3>Useful Links</h3>
                    <ul>
                        <li>Coupons</li>
                        <li>Return Policy</li>
                        <li>Blog post</li>
                        <li>Join Affliates</li>
                    </ul>
                </div>
                <div class="footer-col-4">
                    <h3>Follow us</h3>
                    <ul>
                        <li>FaceBook</li>
                        <li>Twitter</li>
                        <li>Instagram</li>
                        <li>YouTube</li>
                        <li>Threads</li>
                    </ul>
                </div>
            </div>
            <hr>
            <div class="copyright" >
                <p>CopyRight 2023-Vinoth Website</p>
            </div>
        </div>
    </div>
    <!--js toggle menu-->
    

        // your existing menu toggle function

            


    <script>
        function updateCartItem(input) {
            var quantity = input.value;
            var priceElement = input.closest('tr').querySelector('.price');
            var price = parseFloat(priceElement.innerText.replace('Price:$', ''));
            var subtotalElement = input.closest('tr').querySelector('.subtotal');
            var subtotal = quantity * price;
            subtotalElement.innerText = '$' + subtotal.toFixed(2);
            updateTotal();
        }

        function removeCartItem(link) {
            link.closest('tr').remove();
            updateTotal();
        }

        function updateTotal() {
            var subTotal = 0;
            document.querySelectorAll('.subtotal').forEach(function (subtotalElement) {
                subTotal += parseFloat(subtotalElement.innerText.replace('$', ''));
            });

            var tax = subTotal * 0.2; // Assuming tax is 20%
            var total = subTotal + tax;

            document.getElementById('subTotal').innerText = '$' + subTotal.toFixed(2);
            document.getElementById('tax').innerText = '$' + tax.toFixed(2);
            document.getElementById('total').innerText = '$' + total.toFixed(2);
        }
    </script>
    

</body>
</html>
   